---
name: "Release"
on: "workflow_dispatch"
jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.10"
      - name: "Build distribution packages"
        run: make package-check
      - name: "Save distribution directory"
        uses: "actions/upload-artifact@v4"
        with:
          name: "distribution"
          path: |
            dist
  upload:
    name: "Upload"
    needs: "build"
    runs-on: "ubuntu-24.04"
    environment: "release"
    permissions:
      id-token: "write"
    steps:
      - name: "Restore distribution directory"
        uses: "actions/download-artifact@v4"
        with:
          name: "distribution"
          path: |
            dist
      - name: "Upload distribution packages to PyPI"
        uses: "pypa/gh-action-pypi-publish@release/v1"
